### ISSUE TITLE
Failed to set up oxigraph endpoint

### ISSUE THREAD

**Issue by ch-sander** [researchspace/researchspace-docker-compose#3]
issue described here: https://github.com/oxigraph/oxigraph/issues/957

I fail to set up [oxigraph](https://github.com/oxigraph/oxigraph) as an endpoint for ResearchSpace

**Comment by aindlq** [comment]
@ch-sander you can separately configure query and update endpoint for default repository.

Essentially you need to create `runtime-data/config/repositories/default.ttl`:

```

@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix mph: <http://www.researchspace.org/resource/system/repository#> .
@prefix sparqlr: <http://www.openrdf.org/config/repository/sparql#> .

[] a rep:Repository ;
  rep:repositoryID "default" ;
  rdfs:label "Default HTTP SPARQL Repository" ;
  rep:repositoryImpl [
    rep:repositoryType "researchspace:SPARQLRepository" ;
    sparqlr:query-endpoint <http://example.org/sparql> ; # Endpoint to send SPARQL queries to.
    sparqlr:update-endpoint <http://example.org/update> ; # Update endpoint (optional - only if different from the query endpoint)
    mph:quadMode true ; # Flag determining whether the requests for statements should retrieve triples <subj, pred, obj> or quads <subj, pred, obj, named_graph>
  ] .
```

it will overwrite repository specified with `-Dconfig.environment.sparqlEndpoint`.

Through this configuration you can also use repositories that requires basic auth, etc. See more details here - see more details here - https://documentation.researchspace.org/resource/Help:RepositoryManager

**Comment by ch-sander** [comment]
@aindlq Thanks!
With this, I got somewhat further. I now can use oxigraph as default repository, I can query and update the default repository via the SPARQL endpoint (`http://localhost:10214/sparql`). However, both the UI file upload (`http://localhost:10214/resource/Admin:DataImportExport`) and curl at `http://localhost:10214/rdf-graph-store` prompt: 

> **http://oxigraph:7878/query repository is readonly!**

So, this means the definition in `default.ttl`
```sparql
sparql:query-endpoint <http://oxigraph:7878/query>;
sparql:update-endpoint <http://oxigraph:7878/update>;
```
is not accounted for by the API, it seems. Is this a glitch of ResearchSpace or yet another misconfiguration of mine?

I really appreciate your help! And I think this might not really touch on @Tpt's oxigraph and https://github.com/oxigraph/oxigraph/issues/957 but is a ResearchSpace issue.


LOGS:
```
2024-08-11 09:01:09,829 DEBUG [qtp2035070981-20] org.researchspace.rest.endpoint.RDFGraphStoreEndpoint - No graph URI specified. Creating random URI.
2024-08-11 09:01:10,039 ERROR [qtp2035070981-20] org.researchspace.rest.endpoint.RDFGraphStoreEndpoint - Failed to create GRAPH "file://agg_graph.ttl-11-08-2024-11-01-09" : Can't commit transaction. http://oxigraph:7878/query repository is readonly!
2024-08-11 09:01:10,039 DEBUG [qtp2035070981-20] org.researchspace.rest.endpoint.RDFGraphStoreEndpoint - Details:
org.eclipse.rdf4j.repository.RepositoryException: Can't commit transaction. http://oxigraph:7878/query repository is readonly!
```

**Comment by ch-sander** [comment]
Also this setup
```yaml
-Dconfig.environment.sparqlEndpoint=http://oxigraph:7878/update
```
doesn't do the trick!

![grafik](https://github.com/user-attachments/assets/117f0737-2e39-4d80-8bca-360b9edbeca8)

**Comment by ch-sander** [comment]
# Update!

I had the repository set read-only (`mph:writable false`)

Once I changed it to `true`, however, the app fails to load, leading to the 503 error for localhost:10214.

It seems to be due to templates or assets:

```
g17test-oxigraph-1       | Internal server error: The graph GRAPH <http://www.researchspace.org/ontology/PX_profession/context> does not exists
g17test-researchspace-1  | 2024-08-11 09:11:04 WARN  [main] (SPARQLProtocolSession.java:1192) - Server reports problem: null (enable debug logging for full details)
g17test-researchspace-1  | 2024-08-11 09:11:04.428:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5db6b9cd{/,file:///tmp/jetty/jetty-0_0_0_0-8080-ROOT_war-_-any-6157512089489128674.dir/webapp/,UNAVAILABLE}{/var/lib/jetty/webapps/ROOT.war}
```

[log.txt](https://github.com/user-attachments/files/16573177/log.txt)

Is this maybe due to https://github.com/researchspace/researchspace-instance-configurations ?

Simply uploading the two trig files (quads) in the repo into my oxigraph didn't help. However, it created the mentioned `PX-profession` graph, but the next time the error will be 

> org.eclipse.rdf4j.repository.RepositoryException: The graph GRAPH <http://www.researchspace.org/pattern/ancient_periods/P82b_end_of_the_end/context> does not exists

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?graph
WHERE {
  GRAPH ?graph { ?s ?p ?o }
  FILTER(STRSTARTS(STR(?graph), "http://www.researchspace.org"))
}
```

returns 12 graphs:

```
http://www.researchspace.org/ontology/boundingBox/context
http://www.researchspace.org/ontology/PX_physical_description/context
http://www.researchspace.org/ontology/PX_has_video/context
http://www.researchspace.org/instances/fields/E22ManMadeObjectP108iwasproducedbyE12ProductionP4hastimespanE52TimeSpan/context
http://www.researchspace.org/ontology/PX_is_connected/context
http://www.researchspace.org/conservation/fieldDefinition/Structural%20condition/context
http://www.researchspace.org/ontology/viewport/context
http://www.researchspace.org/ontology/PX_has_main_representation/context
http://www.researchspace.org/resource/system/fieldDefinitionContainer/context
http://www.researchspace.org/ontology/PX_profession/context
http://www.researchspace.org/instances/fields/wasusedfor/context
```

`http://www.researchspace.org/pattern/ancient_periods/P82b_end_of_the_end/context` nowhere to be found.

As the app doesn't load, I cannot access the UI `/resource/Platform:fieldDefinitionContainer?repository=assets`. Anyways, maybe the assets repository should not be touched by the default repository in the first place? It seems that the patterns are loaded in the container somewhere and get shadowed or overruled by me custom default repository if set as writable.

**Comment by aindlq** [comment]
@ch-sander what researchspace docker image version are you using? Could you share your .env and docker-compose files

**Comment by ch-sander** [comment]
Of course!
# docker-compose.yml
```yaml
version: "2.2"
services:
  researchspace:
    image: ${RESEARCHSPACE_IMAGE}
    restart: unless-stopped
    mem_limit: ${RESEARCHSPACE_MEMORY}
    mem_reservation: ${RESEARCHSPACE_MEMORY}
    ports:
      - "10214:8080"
    environment:
      # 1. Connect researchspace instance to blazegraph instance, in this case we use internal hostname available only inside docker-compose create network.
      # 2. Set default logging profile to log4j2, other possible options are log4j2-debug.xml, log4j2-trace.xml
      # 3-5. Create storage needed for image upload functionality
      # 6-8. Create temp storage needed for image upload functionality
      # 7. Additional options provided in .env file
      PLATFORM_OPTS: >-
        -Dconfig.environment.sparqlEndpoint=http://oxigraph:7878/query
        -Dlog4j.configurationFile=classpath:org/researchspace/logging/log4j2-debug.xml
        -Dconfig.storage.images.type=nonVersionedFile
        -Dconfig.storage.images.mutable=true
        -Dconfig.storage.images.root=/images
        -Dconfig.storage.tmp.type=nonVersionedFile
        -Dconfig.storage.tmp.mutable=true
        -Dconfig.storage.tmp.root=/tmp-data
        ${RESEARCHSPACE_OPTS}
      JAVA_OPTS: ${RESEARCHSPACE_JAVA_OPTS}
    volumes:
       # mount folder where uploaded images should be stored 
       - ./researchspace/data/images:/images:rw

       # mount folder where temporary files should be stored
       - ./researchspace/data/tmp:/tmp-data:rw

      # mount folder where apps should be stored
       - ./researchspace/apps:/apps:rw
       
       # runtime data folder with config files and ad-hoc templates 
       - ./researchspace/runtime-data:/runtime-data
    depends_on:
      - oxigraph
      - digilib 
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  oxigraph:
    image: oxigraph/oxigraph
    ports:
      - "7878:7878"
    volumes:
     - ./data_oxigraph:/data
    command: ["serve", "--location", "/data", "--bind", "0.0.0.0:7878"]

  # blazegraph:
  #   image: ${BLAZEGRAPH_IMAGE}
  #   restart: unless-stopped
  #   mem_limit: ${BLAZEGRAPH_MEMORY}
  #   mem_reservation: ${BLAZEGRAPH_MEMORY}
  #   ports:
  #     - "10215:8080"
  #   environment:
  #     JAVA_OPTS: ${BLAZEGRAPH_JAVA_OPTS}
  #   volumes:
  #    - ./blazegraph/:/blazegraph-data
  #   logging:
  #    driver: json-file
  #    options:
  #     max-size: "200k"
  #     max-file: "10"

  digilib:
    image: ${DIGILIB_IMAGE}
    restart: unless-stopped
    mem_limit: ${DIGILIB_MEMORY}
    mem_reservation: ${DIGILIB_MEMORY}
    environment:
      BASEDIR_LIST: /var/lib/images
      IIIF_IMAGE_BASE_URL: "http://localhost:10214/proxy/IIIF/"
    volumes:
      - ./researchspace/data/images/file:/var/lib/images:rw
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
```
# .env
```env
# (required) your project name, to have nice container names in the docker-compose setup.
# see https://docs.docker.com/compose/reference/envvars/#compose_project_name
COMPOSE_PROJECT_NAME=g17test

# (required) memory limits for docker containers

# Total amount of memory available for containers
RESEARCHSPACE_MEMORY=1g
BLAZEGRAPH_MEMORY=1g
DIGILIB_MEMORY=500m

# (optional) additional ReseearchSpace runtime options.
# By default increases jetty upload limit to ~100mb
RESEARCHSPACE_OPTS=-Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000

# (optional) additional JVM opts for various applications
# WARNING! Don't set Xmx here, use memory variables above. We use -XX:+UseContainerSupport, see https://merikan.com/2019/04/jvm-in-a-container/ for more details about memory management of Java apps inside docker.
RESEARCHSPACE_JAVA_OPTS=
BLAZEGRAPH_JAVA_OPTS=
DIGILIB_JAVA_OPTS=

# docker images
RESEARCHSPACE_IMAGE=researchspace/platform-ci:latest
BLAZEGRAPH_IMAGE=researchspace/blazegraph:latest
DIGILIB_IMAGE=robcast/digilib:latest
```
# default.ttl
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sparql: <http://www.openrdf.org/config/repository/sparql#> .
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sr: <http://www.openrdf.org/config/repository/sail#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix mph: <http://www.researchspace.org/resource/system/repository#> .
@prefix ephedra: <http://www.researchspace.org/resource/system/ephedra#> .
@prefix fedsail: <http://www.openrdf.org/config/sail/federation#> .

[] a rep:Repository;
  rep:repositoryID "default";
  rdfs:label "Default G17 HTTP SPARQL Repository";
  rep:repositoryImpl [
      rep:repositoryType "researchspace:SPARQLRepository";
      sparql:query-endpoint <http://oxigraph:7878/query>;
      sparql:update-endpoint <http://oxigraph:7878/update>;
      mph:quadMode true;
      mph:writable true
    ] .
```
# assets.ttl
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix proxy: <http://www.openrdf.org/config/repository/proxy#> .
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sr: <http://www.openrdf.org/config/repository/sail#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix mph: <http://www.researchspace.org/resource/system/repository#> .
@prefix ephedra: <http://www.researchspace.org/resource/system/ephedra#> .
@prefix fedsail: <http://www.openrdf.org/config/sail/federation#> .
@prefix sparqlr: <http://www.openrdf.org/config/repository/sparql#> .

[] a rep:Repository;
  rep:repositoryID "assets";
  rdfs:label "assetsrepository for platform.";
  rep:repositoryImpl [
      rep:repositoryType "openrdf:ProxyRepository";
      proxy:proxiedID "default"
    ] .
```
